import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-500 min-w-full min-h-screen text-white">
        <Navbar />
        {children}
      </main>
    </>
  );
};
export default Layout;
