import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-primary min-w-full min-h-screen text-white ">
        <div className="px-5 max-w-3xl mx-auto">
          <Navbar />
          {children}
        </div>
      </main>
    </>
  );
};
export default Layout;
